name: Process Design Tokens

on:
  push:
    paths:
      - "tokens/**" # Trigger only when files in the tokens directory change
  workflow_dispatch: # Allow manual triggering

jobs:
  transform-tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Process tokens
        run: npm run process-tokens

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update CSS variables from design tokens"
          file_pattern: "src/css/variables.css"
