name: Process Design Tokens

on:
  push:
    paths:
      - "tokens/**" # Trigger only when files in the tokens directory change
  workflow_dispatch: # Allow manual triggering

jobs:
  transform-tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          npm install style-dictionary@latest @tokens-studio/sd-transforms@latest

      - name: Process tokens with verbose output
        run: npm run process-tokens -- --verbose
        # This assumes your package.json has a script like:
        # "process-tokens": "style-dictionary build --config style-dictionary.config.js"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update themed CSS variables from design tokens"
          file_pattern: "src/css/_variables-*.css" # Commit all generated theme variable files